// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT6qxdkp3VTMU5-Vn5QfFXRwQubNwoon8',
    appId: '1:649732238325:web:339c0290dd7ba0d7f5cebc',
    messagingSenderId: '649732238325',
    projectId: 'empower-ananya-app-ea362',
    authDomain: 'empower-ananya-app-ea362.firebaseapp.com',
    storageBucket: 'empower-ananya-app-ea362.firebasestorage.app',
    measurementId: 'G-T0EL9LKNW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSm6VCsDWjfx9MSqs5RcHhzjf9NYKim-w',
    appId: '1:649732238325:android:0487ecb332aacae6f5cebc',
    messagingSenderId: '649732238325',
    projectId: 'empower-ananya-app-ea362',
    storageBucket: 'empower-ananya-app-ea362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOwQVmkjvXLc4SC1pLjfiv_Ch8fnHTr68',
    appId: '1:649732238325:ios:eaa0d9fa284c5e63f5cebc',
    messagingSenderId: '649732238325',
    projectId: 'empower-ananya-app-ea362',
    storageBucket: 'empower-ananya-app-ea362.firebasestorage.app',
    iosBundleId: 'com.example.empowerAnanyaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOwQVmkjvXLc4SC1pLjfiv_Ch8fnHTr68',
    appId: '1:649732238325:ios:eaa0d9fa284c5e63f5cebc',
    messagingSenderId: '649732238325',
    projectId: 'empower-ananya-app-ea362',
    storageBucket: 'empower-ananya-app-ea362.firebasestorage.app',
    iosBundleId: 'com.example.empowerAnanyaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT6qxdkp3VTMU5-Vn5QfFXRwQubNwoon8',
    appId: '1:649732238325:web:324b93817bc2d073f5cebc',
    messagingSenderId: '649732238325',
    projectId: 'empower-ananya-app-ea362',
    authDomain: 'empower-ananya-app-ea362.firebaseapp.com',
    storageBucket: 'empower-ananya-app-ea362.firebasestorage.app',
    measurementId: 'G-WZNT5MJBK5',
  );
}
